In [91]:
import torch

In [92]:
import sys
import os

# Add project root to PYTHONPATH
sys.path.append('/Users/venkatkapil24/scratch/nl/torch-nlpp/')

from ase import Atoms
from neighbourlist import NeighbourList

cell = [
    [ 2.460394,  0.0,       0.0     ],
    [-1.26336,   2.044166,  0.0     ],
    [-0.139209, -0.407369,  6.809714]
]

positions = [
    [-0.03480225, -0.10184225, 1.70242850],
    [-0.10440675, -0.30552675, 5.10728550],
    [-0.05691216,  1.26093576, 1.70242850],
    [ 1.11473716,  0.37586124, 5.10728550],
]

carbon = Atoms(
    symbols="CCCC",
    positions=positions,
    cell=cell,
    pbc=True,
)

nl = NeighbourList(
    list_of_configurations=[carbon],
    radius=3,
    batch_size=1,
    device='cpu'
)

nl.load_data()
out = nl.calculate_neighbourlist()
mesh = nl.calculate_batch_lattice_shifts(nl.batch_cells_tensor_list[0], nl.radius)

In [93]:
mesh.unsqueeze(0).shape
mesh = mesh.unsqueeze(0)

In [94]:
str_nl.shape[0], str_nl.shape[1] * str_nl.shape[2]

(4, 300)

In [103]:
str_nl = out[0][0].permute(1, 0, 2)

str_nl = str_nl.reshape((str_nl.shape[0], str_nl.shape[1] * str_nl.shape[2]))

print (str_nl.shape)

print (torch.nonzero(str_nl[0], as_tuple=False))

torch.Size([4, 300])
tensor([[  0],
        [  4],
        [  8],
        [ 12],
        [ 16],
        [ 20],
        [ 24],
        [ 26],
        [ 28],
        [ 30],
        [ 32],
        [ 34],
        [ 36],
        [ 38],
        [ 40],
        [ 42],
        [ 44],
        [ 46],
        [ 48],
        [ 50],
        [ 52],
        [ 54],
        [ 56],
        [ 58],
        [ 60],
        [ 64],
        [ 68],
        [ 72],
        [ 74],
        [ 76],
        [ 78],
        [ 80],
        [ 81],
        [ 82],
        [ 84],
        [ 86],
        [ 88],
        [ 90],
        [ 92],
        [ 93],
        [ 94],
        [ 96],
        [ 98],
        [100],
        [102],
        [104],
        [105],
        [106],
        [108],
        [110],
        [112],
        [114],
        [116],
        [118],
        [120],
        [124],
        [128],
        [132],
        [134],
        [136],
        [138],
        [140],
        [141],
        [142],
        [144],
    

In [60]:
for batch_idx, batch_nl in enumerate(out):
    
    for str_idx, str_nl in enumerate(batch_nl):

        for lattice_dir_idx, lattice_dir in enumerate(str_nl):
                print (lattice_dir_idx, lattice_dir.shape)

0 torch.Size([4, 4])
1 torch.Size([4, 4])
2 torch.Size([4, 4])
3 torch.Size([4, 4])
4 torch.Size([4, 4])
5 torch.Size([4, 4])
6 torch.Size([4, 4])
7 torch.Size([4, 4])
8 torch.Size([4, 4])
9 torch.Size([4, 4])
10 torch.Size([4, 4])
11 torch.Size([4, 4])
12 torch.Size([4, 4])
13 torch.Size([4, 4])
14 torch.Size([4, 4])
15 torch.Size([4, 4])
16 torch.Size([4, 4])
17 torch.Size([4, 4])
18 torch.Size([4, 4])
19 torch.Size([4, 4])
20 torch.Size([4, 4])
21 torch.Size([4, 4])
22 torch.Size([4, 4])
23 torch.Size([4, 4])
24 torch.Size([4, 4])
25 torch.Size([4, 4])
26 torch.Size([4, 4])
27 torch.Size([4, 4])
28 torch.Size([4, 4])
29 torch.Size([4, 4])
30 torch.Size([4, 4])
31 torch.Size([4, 4])
32 torch.Size([4, 4])
33 torch.Size([4, 4])
34 torch.Size([4, 4])
35 torch.Size([4, 4])
36 torch.Size([4, 4])
37 torch.Size([4, 4])
38 torch.Size([4, 4])
39 torch.Size([4, 4])
40 torch.Size([4, 4])
41 torch.Size([4, 4])
42 torch.Size([4, 4])
43 torch.Size([4, 4])
44 torch.Size([4, 4])
45 torch.Size([4, 4]

In [36]:
for i, m in enumerate(mesh):
    if m[0].item() == -1: print (i, m)

15 tensor([-1, -2, -1], dtype=torch.int8)
16 tensor([-1, -2,  0], dtype=torch.int8)
17 tensor([-1, -2,  1], dtype=torch.int8)
18 tensor([-1, -1, -1], dtype=torch.int8)
19 tensor([-1, -1,  0], dtype=torch.int8)
20 tensor([-1, -1,  1], dtype=torch.int8)
21 tensor([-1,  0, -1], dtype=torch.int8)
22 tensor([-1,  0,  0], dtype=torch.int8)
23 tensor([-1,  0,  1], dtype=torch.int8)
24 tensor([-1,  1, -1], dtype=torch.int8)
25 tensor([-1,  1,  0], dtype=torch.int8)
26 tensor([-1,  1,  1], dtype=torch.int8)
27 tensor([-1,  2, -1], dtype=torch.int8)
28 tensor([-1,  2,  0], dtype=torch.int8)
29 tensor([-1,  2,  1], dtype=torch.int8)


In [47]:
out[0][0][17]

tensor([[ True, False, False, False],
        [False,  True, False, False],
        [ True,  True,  True, False],
        [False,  True, False,  True]])

In [50]:
from vesin import ase_neighbor_list


i, j, S, d = ase_neighbor_list("ijSd", carbon, cutoff=3.0)

In [52]:
i[7]

0

In [44]:
j[7]

2

In [45]:
S[7]

array([-1, -1,  0], dtype=int32)